### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zacanger** [zacanger/zeelib#14]
Roadmap/TODO list (for no release in particular):

- [x] Update all deps
- [x] Remove more deprecated functions, if any
- [x] Don't version control `dist`
- [ ] Add tests for all functions
- [ ] Remove all weak types
- [ ] Allow for `import foo from 'zeelib/foo'` (instead of `import foo from 'zeelib/dist/foo'`)
- [ ] Finish adding Flow
- [ ] Make TypeScript types available for consumers
- [ ] Doc
  - [ ] TOC sections
  - [ ] Fix all functions that are wrapped in `curry` so documentation.js actually knows what to do with them
  - [x] Fix newlines in docs
  - [x] gh-pages site
  - [x] Make sure all `imports` (and whatever) are _above_ jsdoc comments

**Comment by zacanger** [comment]
Moving this to ROADMAP.md
