### ISSUE TITLE
0.9.0 Roadmap

### ISSUE THREAD

**Issue by zacanger** [zacanger/zeelib#8]
- [x] Clean up all functions
- [x] kebab-case all js
- [x] Change `objectToString` to call in implementation rather than usage
- [x] Deprecate:
  - [x] Duplicates
  - [x] Things that can be generalized
  - [x] Garbage
  - [x] Polyfills
- [x] Doc:
  - [x] Better param names
  - [x] Real changelog
