### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by zacanger** [zacanger/zeelib#9]
- [x] Remove all deprecated functions
- [x] Make Flow types available for consumers
- [x] Change all functions to be easily curryable (data last)
- [x] Make `curry` more flexible
- [x] Make `uncurry` flexible
- [x] npm5
- [x] Doc:
  - [x] Examples for every function
